var map = {
    'mapArray': [
    	['Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar'],
    	['Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar'],
    	['Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar'],
    	['Ar','Ar','Do','Ar','Ar','Ar','Ar','Ar','Do','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Do','Ar','Ar','Ar','Ar','Ar','Do','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','Ar','El'],
    	['Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','Rd','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El'],
    	['Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','Dt','El']
    ],
    
    'numCols': function() { 
        return (typeof this.mapArray[0] !== 'undefined')? this.mapArray[0].length: 0; 
    },
    'numRows': function() { return this.mapArray.length; },
    'name': 'Default Map',
    'toString': function() { return 'MinerJs Map Object'; }
};